### ISSUE TITLE
typeof null

### ISSUE THREAD

**Issue by xuekai-china** [YvetteLau/Blog#9]
你确定 typeof === ‘object’ || typeof === 'function' 的都是复杂类型吗？

**Comment by YvetteLau** [comment]
> 你确定 typeof === ‘object’ || typeof === 'function' 的都是复杂类型吗？

请问哪些情况，typeof为object或者是function的时候，是简单数据类型哈~
不好意思，可能我这方面知识还不足，请赐教~非常感谢~

**Comment by xuekai-china** [comment]
> > 你确定typeof ==='object'|| typeof ==='function'的都是复杂类型吗？
> 
> 请问哪些情况的typeof为对象或者是功能的时候，是简单数据类型哈〜
> 不好意思，可能我这方面知识还不足，请赐教非常感谢

标题 typeof null      return  object

**Comment by YvetteLau** [comment]
> > > 你确定typeof ==='object'|| typeof ==='function'的都是复杂类型吗？
> > 
> > 
> > 请问哪些情况的typeof为对象或者是功能的时候，是简单数据类型哈〜
> > 不好意思，可能我这方面知识还不足，请赐教非常感谢
> 
> 标题 typeof null return object

    if (data && (typeof data === 'object' || typeof data === 'function')) {
        return true;
    }
是否是复杂类型，我是这样判断的，首先已经排除了data是null的情况了~

**Comment by xuekai-china** [comment]
> > > > 你确定typeof ==='object'|| typeof ==='function'的都是复杂类型吗？
> > > 
> > > 
> > > 请问哪些情况的typeof为对象或者是功能的时候，是简单数据类型哈〜
> > > 不好意思，可能我这方面知识还不足，请赐教非常感谢
> > 
> > 
> > 标题 typeof null return object
> 
> ```
> if (data && (typeof data === 'object' || typeof data === 'function')) {
>     return true;
> }
> ```
> 是否是复杂类型，我是这样判断的，首先已经排除了data是null的情况了~
嗯嗯 不好意思 没看仔细
